# 1. Importação de Bibliotecas e carregamento de dados

### 1.1. Biblioteca

In [1]:
import pandas as pd
import numpy as np

### 1.2. Carregamento de dados e visualização

In [2]:
df_2022 = pd.read_csv('https://github.com/JCDIAMANTINO/Datathon-Passos-Magicos-Fase-5/raw/refs/heads/main/Dados_datathon/pede_2022.csv', sep =';')
df_2023 = pd.read_csv ('https://github.com/JCDIAMANTINO/Datathon-Passos-Magicos-Fase-5/raw/refs/heads/main/Dados_datathon/Pede_2023.csv',sep=';')
df_2024 = pd.read_csv ('https://github.com/JCDIAMANTINO/Datathon-Passos-Magicos-Fase-5/raw/refs/heads/main/Dados_datathon/pede_2024.csv',sep=';')

In [3]:
print(df_2022.head())

     RA  Fase Turma     Nome  Ano nasc  Idade 22  Gênero  Ano ingresso  \
0  RA-1   7.0     A  Aluno-1    2003.0      19.0  Menina        2016.0
1  RA-2   7.0     A  Aluno-2    2005.0      17.0  Menina        2017.0
2  RA-3   7.0     A  Aluno-3    2005.0      17.0  Menina        2016.0
3  RA-4   7.0     A  Aluno-4    2005.0      17.0  Menino        2017.0
4  RA-5   7.0     A  Aluno-5    2005.0      17.0  Menina        2016.0

  Instituição de ensino  Pedra 20  ... Inglês Indicado Atingiu PV    IPV  \
0        Escola Pública  Ametista  ...    6,0      Sim        Não  7,278
1          Rede Decisão  Ametista  ...    9,7      Não        Não  6,778
2          Rede Decisão  Ametista  ...    6,9      Não        Não  7,556
3          Rede Decisão  Ametista  ...    8,7      Não        Não  5,278
4          Rede Decisão  Ametista  ...    5,7      Não        Não  7,389

      IAN               Fase ideal  Defas  \
0   5,000  Fase 8 (Universitários)   -1.0
1  10,000           Fase 7 (3º EM)    0.0
2  10,000           Fase 7 (3º EM)    0.0
3  10,000           Fase 7 (3º EM)    0.0
4  10,000           Fase 7 (3º EM)    0.0

                                        Destaque IEG  \
0  Melhorar: Melhorar a sua entrega de lições de ...
1  Melhorar: Melhorar a sua entrega de lições de ...
2    Destaque: A sua boa entrega das lições de casa.
3  Melhorar: Melhorar a sua entrega de lições de ...
4    Destaque: A sua boa entrega das lições de casa.

                                        Destaque IDA  \
0  Melhorar: Empenhar-se mais nas aulas e avaliaç...
1  Melhorar: Empenhar-se mais nas aulas e avaliaç...
2  Melhorar: Empenhar-se mais nas aulas e avaliaç...
3  Melhorar: Empenhar-se mais nas aulas e avaliaç...
4  Melhorar: Empenhar-se mais nas aulas e avaliaç...

                                        Destaque IPV
0  Melhorar: Integrar-se mais aos Princípios Pass...
1  Melhorar: Integrar-se mais aos Princípios Pass...
2  Destaque: A sua boa integração aos Princípios ...
3  Melhorar: Integrar-se mais aos Princípios Pass...
4  Melhorar: Integrar-se mais aos Princípios Pass...

[5 rows x 42 columns]

In [4]:
print(df_2023.head())

       RA  Fase INDE 2023 Pedra 2023           Turma Nome Anonimizado  \
0  RA-861  ALFA   9,31095    Topázio  ALFA A - G0/G1        Aluno-861
1  RA-862  ALFA    8,2212    Topázio  ALFA A - G0/G1        Aluno-862
2  RA-863  ALFA   5,92975    Quartzo  ALFA A - G0/G1        Aluno-863
3  RA-864  ALFA     7,034   Ametista  ALFA A - G0/G1        Aluno-864
4  RA-865  ALFA    8,1552    Topázio  ALFA A - G0/G1        Aluno-865

  Data de Nasc       Idade     Gênero  Ano ingresso  ... Indicado Atingiu PV  \
0    6/17/2015           8   Feminino          2023  ...      NaN        NaN
1    5/31/2014           9  Masculino          2023  ...      NaN        NaN
2    2/25/2016           7  Masculino          2023  ...      NaN        NaN
3   03/12/2015  08/01/1900   Feminino          2023  ...      NaN        NaN
4   11/13/2014           8  Masculino          2023  ...      NaN        NaN

     IPV IAN            Fase Ideal Defasagem  Destaque IEG  Destaque IDA  \
0   8,92  10    ALFA (1° e 2° ano)         0           NaN           NaN
1  8,585   5  Fase 1 (3° e 4° ano)        -1           NaN           NaN
2   6,26  10    ALFA (1° e 2° ano)         0           NaN           NaN
3    8,5  10    ALFA (1° e 2° ano)         0           NaN           NaN
4  7,915  10    ALFA (1° e 2° ano)         0           NaN           NaN

   Destaque IPV  Destaque IPV.1
0           NaN             NaN
1           NaN             NaN
2           NaN             NaN
3           NaN             NaN
4           NaN             NaN

[5 rows x 48 columns]

In [5]:
print(df_2024.head())

        RA  Fase    INDE 2024 Pedra 2024           Turma Nome Anonimizado  \
0  RA-1275  ALFA  7,611366667   Ametista  ALFA A - G0/G1       Aluno-1275
1  RA-1276  ALFA  8,002866667    Topázio  ALFA A - G0/G1       Aluno-1276
2  RA-1277  ALFA       7,9522   Ametista  ALFA A - G0/G1       Aluno-1277
3   RA-868  ALFA  7,156366667   Ametista  ALFA A - G0/G1        Aluno-868
4  RA-1278  ALFA       5,4442    Quartzo  ALFA A - G0/G1       Aluno-1278

  Data de Nasc  Idade     Gênero  Ano ingresso  ...  IPV IAN  \
0   28/07/2016      8  Masculino          2024  ...  5,4  10
1   16/10/2016      8   Feminino          2024  ...  7,1  10
2   16/08/2016      8  Masculino          2024  ...  7,0  10
3   08/11/2015      8  Masculino          2023  ...  7,2   5
4   22/03/2015      9  Masculino          2024  ...  4,2   5

             Fase Ideal Defasagem Destaque IEG Destaque IDA Destaque IPV  \
0    ALFA (1° e 2° ano)         0          NaN          NaN          NaN
1    ALFA (1° e 2° ano)         0          NaN          NaN          NaN
2    ALFA (1° e 2° ano)         0          NaN          NaN          NaN
3  Fase 1 (3° e 4° ano)        -1          NaN          NaN          NaN
4  Fase 1 (3° e 4° ano)        -1          NaN          NaN          NaN

                              Escola  Ativo/ Inativo  Ativo/ Inativo.1
0              EE Chácara Florida II        Cursando          Cursando
1              EE Chácara Florida II        Cursando          Cursando
2  EE Dom Pedro Villas Boas de Souza        Cursando          Cursando
3              EE Chácara Florida II        Cursando          Cursando
4          EM Etelvina Delfim Simões        Cursando          Cursando

[5 rows x 50 columns]

# 2. Tratamento dos dados

###2.1. Checagem iniciais

In [6]:
# Verificação da quantidade de linhas e colunas
df_2022.shape

(861, 42)

In [7]:
df_2023.shape

(1014, 48)

In [8]:
df_2024.shape

(1156, 50)

In [9]:
# Verificação das informações do DataFrame
df_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 861 entries, 0 to 860
Data columns (total 42 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     860 non-null    object
 1   Fase                   860 non-null    float64
 2   Turma                  860 non-null    object
 3   Nome                   860 non-null    object
 4   Ano nasc               860 non-null    float64
 5   Idade 22               860 non-null    float64
 6   Gênero                 860 non-null    object
 7   Ano ingresso           860 non-null    float64
 8   Instituição de ensino  860 non-null    object
 9   Pedra 20               323 non-null    object
 10  Pedra 21               462 non-null    object
 11  Pedra 22               860 non-null    object
 12  INDE 22                860 non-null    object
 13  Cg                     860 non-null    object
 14  Cf                     860 non-null    float64
 15  Ct                     860 non-null    float64
 16  Nº Av                  860 non-null    float64
 17  Avaliador1             860 non-null    object
 18  Rec Av1                860 non-null    object
 19  Avaliador2             860 non-null    object
 20  Rec Av2                860 non-null    object
 21  Avaliador3             534 non-null    object
 22  Rec Av3                860 non-null    object
 23  Avaliador4             310 non-null    object
 24  Rec Av4                296 non-null    object
 25  IAA                    860 non-null    object
 26  IEG                    860 non-null    object
 27  IPS                    860 non-null    object
 28  Rec Psicologia         860 non-null    object
 29  IDA                    860 non-null    object
 30  Matem                  858 non-null    object
 31  Portug                 858 non-null    object
 32  Inglês                 283 non-null    object
 33  Indicado               860 non-null    object
 34  Atingiu PV             860 non-null    object
 35  IPV                    860 non-null    object
 36  IAN                    860 non-null    object
 37  Fase ideal             860 non-null    object
 38  Defas                  860 non-null    float64
 39  Destaque IEG           860 non-null    object
 40  Destaque IDA           860 non-null    object
 41  Destaque IPV           860 non-null    object
dtypes: float64(8), object(34)
memory usage: 282.6+ KB

In [10]:
df_2023.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 48 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     1014 non-null   object
 1   Fase                   1014 non-null   object
 2   INDE 2023              1014 non-null   object
 3   Pedra 2023             1014 non-null   object
 4   Turma                  1014 non-null   object
 5   Nome Anonimizado       1014 non-null   object
 6   Data de Nasc           1014 non-null   object
 7   Idade                  1014 non-null   object
 8   Gênero                 1014 non-null   object
 9   Ano ingresso           1014 non-null   int64
 10  Instituição de ensino  1014 non-null   object
 11  Pedra 20               240 non-null    object
 12  Pedra 21               335 non-null    object
 13  Pedra 22               600 non-null    object
 14  Pedra 23               0 non-null      float64
 15  INDE 22                600 non-null    object
 16  INDE 23                0 non-null      float64
 17  Cg                     0 non-null      float64
 18  Cf                     0 non-null      float64
 19  Ct                     0 non-null      float64
 20  Nº Av                  938 non-null    float64
 21  Avaliador1             938 non-null    object
 22  Rec Av1                0 non-null      float64
 23  Avaliador2             938 non-null    object
 24  Rec Av2                0 non-null      float64
 25  Avaliador3             707 non-null    object
 26  Rec Av3                0 non-null      float64
 27  Avaliador4             334 non-null    object
 28  Rec Av4                0 non-null      float64
 29  IAA                    951 non-null    object
 30  IEG                    938 non-null    object
 31  IPS                    1014 non-null   object
 32  IPP                    1014 non-null   object
 33  Rec Psicologia         0 non-null      float64
 34  IDA                    938 non-null    object
 35  Mat                    937 non-null    object
 36  Por                    937 non-null    object
 37  Ing                    334 non-null    object
 38  Indicado               0 non-null      float64
 39  Atingiu PV             0 non-null      float64
 40  IPV                    1014 non-null   object
 41  IAN                    1014 non-null   object
 42  Fase Ideal             1014 non-null   object
 43  Defasagem              1014 non-null   int64
 44  Destaque IEG           0 non-null      float64
 45  Destaque IDA           0 non-null      float64
 46  Destaque IPV           0 non-null      float64
 47  Destaque IPV.1         0 non-null      float64
dtypes: float64(17), int64(2), object(29)
memory usage: 380.4+ KB

In [11]:
df_2024.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1156 entries, 0 to 1155
Data columns (total 50 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   RA                     1156 non-null   object
 1   Fase                   1156 non-null   object
 2   INDE 2024              1156 non-null   object
 3   Pedra 2024             1156 non-null   object
 4   Turma                  1156 non-null   object
 5   Nome Anonimizado       1156 non-null   object
 6   Data de Nasc           1156 non-null   object
 7   Idade                  1156 non-null   int64
 8   Gênero                 1156 non-null   object
 9   Ano ingresso           1156 non-null   int64
 10  Instituição de ensino  1155 non-null   object
 11  Pedra 20               191 non-null    object
 12  Pedra 21               264 non-null    object
 13  Pedra 22               472 non-null    object
 14  Pedra 23               765 non-null    object
 15  INDE 22                472 non-null    object
 16  INDE 23                765 non-null    object
 17  Cg                     0 non-null      float64
 18  Cf                     0 non-null      float64
 19  Ct                     0 non-null      float64
 20  Nº Av                  1156 non-null   int64
 21  Avaliador1             1029 non-null   object
 22  Rec Av1                0 non-null      float64
 23  Avaliador2             1029 non-null   object
 24  Rec Av2                0 non-null      float64
 25  Avaliador3             793 non-null    object
 26  Avaliador4             407 non-null    object
 27  Avaliador5             148 non-null    object
 28  Avaliador6             6 non-null      object
 29  IAA                    1054 non-null   object
 30  IEG                    1156 non-null   object
 31  IPS                    1156 non-null   object
 32  IPP                    1156 non-null   object
 33  Rec Psicologia         0 non-null      float64
 34  IDA                    1156 non-null   object
 35  Mat                    1051 non-null   object
 36  Por                    1050 non-null   object
 37  Ing                    474 non-null    object
 38  Indicado               0 non-null      float64
 39  Atingiu PV             0 non-null      float64
 40  IPV                    1156 non-null   object
 41  IAN                    1156 non-null   object
 42  Fase Ideal             1156 non-null   object
 43  Defasagem              1156 non-null   int64
 44  Destaque IEG           0 non-null      float64
 45  Destaque IDA           0 non-null      float64
 46  Destaque IPV           0 non-null      float64
 47  Escola                 1155 non-null   object
 48  Ativo/ Inativo         1156 non-null   object
 49  Ativo/ Inativo.1       1156 non-null   object
dtypes: float64(11), int64(4), object(35)
memory usage: 451.7+ KB

In [12]:
# Verificação de valores nulos
df_2022.isnull().sum()

RA                         1
Fase                       1
Turma                      1
Nome                       1
Ano nasc                   1
Idade 22                   1
Gênero                     1
Ano ingresso               1
Instituição de ensino      1
Pedra 20                 538
Pedra 21                 399
Pedra 22                   1
INDE 22                    1
Cg                         1
Cf                         1
Ct                         1
Nº Av                      1
Avaliador1                 1
Rec Av1                    1
Avaliador2                 1
Rec Av2                    1
Avaliador3               327
Rec Av3                    1
Avaliador4               551
Rec Av4                  565
IAA                        1
IEG                        1
IPS                        1
Rec Psicologia             1
IDA                        1
Matem                      3
Portug                     3
Inglês                   578
Indicado                   1
Atingiu PV                 1
IPV                        1
IAN                        1
Fase ideal                 1
Defas                      1
Destaque IEG               1
Destaque IDA               1
Destaque IPV               1
dtype: int64

In [13]:
df_2023.isnull().sum()

RA                          0
Fase                        0
INDE 2023                   0
Pedra 2023                  0
Turma                       0
Nome Anonimizado            0
Data de Nasc                0
Idade                       0
Gênero                      0
Ano ingresso                0
Instituição de ensino       0
Pedra 20                  774
Pedra 21                  679
Pedra 22                  414
Pedra 23                 1014
INDE 22                   414
INDE 23                  1014
Cg                       1014
Cf                       1014
Ct                       1014
Nº Av                      76
Avaliador1                 76
Rec Av1                  1014
Avaliador2                 76
Rec Av2                  1014
Avaliador3                307
Rec Av3                  1014
Avaliador4                680
Rec Av4                  1014
IAA                        63
IEG                        76
IPS                         0
IPP                         0
Rec Psicologia           1014
IDA                        76
Mat                        77
Por                        77
Ing                       680
Indicado                 1014
Atingiu PV               1014
IPV                         0
IAN                         0
Fase Ideal                  0
Defasagem                   0
Destaque IEG             1014
Destaque IDA             1014
Destaque IPV             1014
Destaque IPV.1           1014
dtype: int64

In [14]:
df_2024.isnull().sum()

RA                          0
Fase                        0
INDE 2024                   0
Pedra 2024                  0
Turma                       0
Nome Anonimizado            0
Data de Nasc                0
Idade                       0
Gênero                      0
Ano ingresso                0
Instituição de ensino       1
Pedra 20                  965
Pedra 21                  892
Pedra 22                  684
Pedra 23                  391
INDE 22                   684
INDE 23                   391
Cg                       1156
Cf                       1156
Ct                       1156
Nº Av                       0
Avaliador1                127
Rec Av1                  1156
Avaliador2                127
Rec Av2                  1156
Avaliador3                363
Avaliador4                749
Avaliador5               1008
Avaliador6               1150
IAA                       102
IEG                         0
IPS                         0
IPP                         0
Rec Psicologia           1156
IDA                         0
Mat                       105
Por                       106
Ing                       682
Indicado                 1156
Atingiu PV               1156
IPV                         0
IAN                         0
Fase Ideal                  0
Defasagem                   0
Destaque IEG             1156
Destaque IDA             1156
Destaque IPV             1156
Escola                      1
Ativo/ Inativo              0
Ativo/ Inativo.1            0
dtype: int64

###2.2. Ajuste e padronização das features

In [15]:
# Adicionando o ano de referência

df_2022['ano'] = 2022
df_2023['ano'] = 2023
df_2024['ano'] = 2024

# ---------------------------------------------------------
# PADRONIZAÇÃO DO DATASET DE 2022
# ---------------------------------------------------------
df_2022_tratado = df_2022.rename(columns={
    'RA': 'ra',                                           # Registro do Aluno
    'Nome': 'nome',                                       # Nome do Aluno (Dados estão Anonimizados)
    'Idade 22': 'idade',                                  # Idade do Aluno
    'Gênero': 'genero',                                   # Gênero do aluno
    'Fase': 'fase',                                       # Fase é o Nível de Aprendizado do Aluno
    'Turma': 'turma',                                     # Número da Turma de cada fase (1A, 1B)
    'Ano ingresso': 'ano_ingresso',                       # Ano que o Aluno Ingressou na Passos Mágicos
    'Instituição de ensino': 'instituicao_ensino',        # Instituição de Ensino do Aluno
    'Rec Psicologia': 'rec_psicologia',
    'Indicado': 'indicado',

    # Indicadores e Métricas
    'INDE 22': 'inde',                                    # Índice do Desenvolvimento Educacional (Métrica Geral)
    'Pedra 22': 'pedra',                                  # Classificação do Aluno (Quartzo, Ágata, Ametista, Topázio)
    'IAA': 'iaa',                                         # Indicador de Auto Avaliação
    'IEG': 'ieg',                                         # Indicador de Engajamento
    'IPS': 'ips',                                         # Indicador Psicossocial
    'IDA': 'ida',                                         # Indicador de Aprendizagem
    'IPV': 'ipv',                                         # Indicador de Ponto de Virada
    'IAN': 'ian',                                         # Indicador de Adequação ao Nível

    # Notas
    'Matem': 'nota_mat',                                  # Média das Notas de Matemática
    'Portug': 'nota_por',                                 # Média das Notas de Português
    'Inglês': 'nota_ing',                                 # Média das Notas de Inglês

    # Status
    'Atingiu PV': 'atingiu_pv',                           # Booleano que sinaliza se o Aluno atingiu o Ponto de Virada
    'Fase ideal': 'fase_ideal',                           # Nível (Fase) ideal do Aluno
    'Defas': 'defasagem'                                  # Nível de defasagem do aluno
})


# ---------------------------------------------------------
# PADRONIZAÇÃO DO DATASET DE 2023
# ---------------------------------------------------------
df_2023_tratado = df_2023.rename(columns={
    'RA': 'ra',
    'Nome Anonimizado': 'nome',
    'Idade': 'idade',
    'Gênero': 'genero',
    'Fase': 'fase',
    'Turma': 'turma',
    'Ano ingresso': 'ano_ingresso',
    'Instituição de ensino': 'instituicao_ensino',
    'Rec Psicologia': 'rec_psicologia',
    'Indicado': 'indicado',

    'INDE 2023': 'inde',
    'Pedra 2023': 'pedra',
    'IAA': 'iaa',
    'IEG': 'ieg',
    'IPS': 'ips',
    'IDA': 'ida',
    'IPV': 'ipv',
    'IAN': 'ian',
    'IPP': 'ipp',                                         # Indicador Psicopedagógico (Inserido em 2023)

    'Mat': 'nota_mat',
    'Por': 'nota_por',
    'Ing': 'nota_ing',

    'Atingiu PV': 'atingiu_pv',
    'Fase Ideal': 'fase_ideal',
    'Defasagem': 'defasagem'
})

# ---------------------------------------------------------
# PADRONIZAÇÃO DO DATASET DE 2024
# ---------------------------------------------------------
df_2024_tratado = df_2024.rename(columns={
    'RA': 'ra',
    'Nome Anonimizado': 'nome',
    'Idade': 'idade',
    'Gênero': 'genero',
    'Fase': 'fase',
    'Turma': 'turma',
    'Ano ingresso': 'ano_ingresso',
    'Instituição de ensino': 'instituicao_ensino',
    'Rec Psicologia': 'rec_psicologia',
    'Indicado': 'indicado',

    'INDE 2024': 'inde',
    'Pedra 2024': 'pedra',
    'IAA': 'iaa',
    'IEG': 'ieg',
    'IPS': 'ips',
    'IDA': 'ida',
    'IPV': 'ipv',
    'IAN': 'ian',
    'IPP': 'ipp',

    'Mat': 'nota_mat',
    'Por': 'nota_por',
    'Ing': 'nota_ing',

    'Fase Ideal': 'fase_ideal',
    'Defasagem': 'defasagem'
})

### 2.3. Filtros e Concatenação

In [16]:

# Listando as colunas finais

colunas_finais = [
    'ano', 'ra', 'nome', 'idade', 'genero', 'fase', 'turma', 'ano_ingresso',
    'instituicao_ensino', 'rec_psicologia', 'indicado',
    'inde', 'pedra', 'fase_ideal', 'defasagem', 'atingiu_pv',
    'iaa', 'ieg', 'ips', 'ida', 'ipv', 'ian', 'ipp',
    'nota_mat', 'nota_por', 'nota_ing'
]

# Filtrando os data-frames

df_22_filtrado = df_2022_tratado[[col for col in colunas_finais if col in df_2022_tratado.columns]]
df_23_filtrado = df_2023_tratado[[col for col in colunas_finais if col in df_2023_tratado.columns]]
df_24_filtrado = df_2024_tratado[[col for col in colunas_finais if col in df_2024_tratado.columns]]

# Juntando as colunas para o dataframe final

df_final = pd.concat([df_22_filtrado, df_23_filtrado, df_24_filtrado], ignore_index=True)

In [17]:
# Visualizando o resultado
print(f"O Dataset consolidado {df_final.shape[0]} linhas e {df_final.shape[1]} colunas.")
display(df_final.head())

O Dataset consolidado 3031 linhas e 26 colunas.

,ano,ra,nome,idade,genero,fase,turma,ano_ingresso,instituicao_ensino,rec_psicologia,...,iaa,ieg,ips,ida,ipv,ian,nota_mat,nota_por,nota_ing,ipp
0,2022,RA-1,Aluno-1,19.0,Menina,7.0,A,2016.0,Escola Pública,Requer avaliação,...,"8,3","4,1","5,6","4,0","7,278","5,000","2,7","3,5","6,0",NaN
1,2022,RA-2,Aluno-2,17.0,Menina,7.0,A,2017.0,Rede Decisão,Sem limitações,...,"8,8","5,2","6,3","6,8","6,778","10,000","6,3","4,5","9,7",NaN
2,2022,RA-3,Aluno-3,17.0,Menina,7.0,A,2016.0,Rede Decisão,Sem limitações,...,"0,0","7,9","5,6","5,6","7,556","10,000","5,8","4,0","6,9",NaN
3,2022,RA-4,Aluno-4,17.0,Menino,7.0,A,2017.0,Rede Decisão,Requer avaliação,...,"8,8","4,5","5,6","5,0","5,278","10,000","2,8","3,5","8,7",NaN
4,2022,RA-5,Aluno-5,17.0,Menina,7.0,A,2016.0,Rede Decisão,Requer avaliação,...,"7,9","8,6","5,6","5,2","7,389","10,000","7,0","2,9","5,7",NaN

In [18]:
# Visualizando os tipos de dados do df_final

df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3031 entries, 0 to 3030
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ano                 3031 non-null   int64
 1   ra                  3030 non-null   object
 2   nome                3030 non-null   object
 3   idade               3030 non-null   object
 4   genero              3030 non-null   object
 5   fase                3030 non-null   object
 6   turma               3030 non-null   object
 7   ano_ingresso        3030 non-null   float64
 8   instituicao_ensino  3029 non-null   object
 9   rec_psicologia      860 non-null    object
 10  indicado            860 non-null    object
 11  inde                3030 non-null   object
 12  pedra               3030 non-null   object
 13  fase_ideal          3030 non-null   object
 14  defasagem           3030 non-null   float64
 15  atingiu_pv          860 non-null    object
 16  iaa                 2865 non-null   object
 17  ieg                 2954 non-null   object
 18  ips                 3030 non-null   object
 19  ida                 2954 non-null   object
 20  ipv                 3030 non-null   object
 21  ian                 3030 non-null   object
 22  nota_mat            2846 non-null   object
 23  nota_por            2845 non-null   object
 24  nota_ing            1091 non-null   object
 25  ipp                 2170 non-null   object
dtypes: float64(2), int64(1), object(23)
memory usage: 615.8+ KB

### 2.4 Realizando ajustes no df_final

In [19]:
# Ajustando colunas númericas decimais (Dtype "object")
colunas_numericas = [
    'inde', 'iaa', 'ieg', 'ips', 'ida', 'ipv', 'ian', 'ipp',
    'nota_mat', 'nota_por', 'nota_ing'
]

# Substituindo vírgula (,) por ponto (.) e células vazias
for col in colunas_numericas:
    if col in df_final.columns:
      if df_final[col].dtype == 'object':
        df_final[col] = df_final[col].str.replace(',', '.', regex=False)
      df_final[col] = pd.to_numeric(df_final[col], errors='coerce')

In [20]:
# Convertendo Idade, Fase e Ano de Ingresso para inteiros
colunas_inteiras = ['idade', 'ano_ingresso', 'fase']
for col in colunas_inteiras:
    if col in df_final.columns:
        if df_final[col].dtype == 'object':
            df_final[col] = df_final[col].astype(str).str.extract(r'(\d+)')[0]
        df_final[col] = pd.to_numeric(df_final[col], errors='coerce').astype('Int64')

### 2.5 Verificação de conteúdo das features e realizando ajustes

**Numéricas:** idade (anos), ano_ingresso, notas acadêmicas (nota_mat, nota_por – escala de 0 a 10) e os indicadores de desempenho da instituição (inde, iaa, ieg, ips, ida, ipv, ian, ipp – escala de 0 a 10). *Observação:* o dataset original contém inconsistências de formatação; no tratamento, os tipos foram convertidos para float e os dados faltantes foram imputados utilizando a mediana.

**Ordinais (escalas):** fase (nível de aprendizado do aluno na ONG, ex: Alfa, Fase 1 até Fase 8), defasagem (grau de atraso/avanço escolar) e pedra (classificação evolutiva de desempenho: Quartzo, Ágata, Ametista, Topázio). *Observação:* os textos da coluna pedra foram padronizados para corrigir divergências de digitação e acentuação.

**Categóricas:** genero (Masculino, Feminino), turma e fase_ideal. (Identificadores únicos excluídos da modelagem: ra e nome).

In [21]:
print (df_final.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3031 entries, 0 to 3030
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ano                 3031 non-null   int64
 1   ra                  3030 non-null   object
 2   nome                3030 non-null   object
 3   idade               3030 non-null   Int64
 4   genero              3030 non-null   object
 5   fase                2603 non-null   Int64
 6   turma               3030 non-null   object
 7   ano_ingresso        3030 non-null   Int64
 8   instituicao_ensino  3029 non-null   object
 9   rec_psicologia      860 non-null    object
 10  indicado            860 non-null    object
 11  inde                2845 non-null   float64
 12  pedra               3030 non-null   object
 13  fase_ideal          3030 non-null   object
 14  defasagem           3030 non-null   float64
 15  atingiu_pv          860 non-null    object
 16  iaa                 2865 non-null   float64
 17  ieg                 2954 non-null   float64
 18  ips                 2846 non-null   float64
 19  ida                 2852 non-null   float64
 20  ipv                 2852 non-null   float64
 21  ian                 3030 non-null   float64
 22  nota_mat            2846 non-null   float64
 23  nota_por            2845 non-null   float64
 24  nota_ing            1091 non-null   float64
 25  ipp                 1992 non-null   float64
dtypes: Int64(3), float64(12), int64(1), object(10)
memory usage: 624.7+ KB
None

In [22]:
df_final.nunique()

ano                      3
ra                    1661
nome                  1661
idade                   21
genero                   4
fase                    10
turma                  120
ano_ingresso             9
instituicao_ensino      12
rec_psicologia           5
indicado                 2
inde                  2704
pedra                    8
fase_ideal              17
defasagem                9
atingiu_pv               2
iaa                     38
ieg                     77
ips                     35
ida                     95
ipv                    595
ian                      3
nota_mat                79
nota_por                84
nota_ing                84
ipp                    106
dtype: int64

In [23]:
df_definitivo = df_final.copy()

# Removendo colunas desnecessárias e linhas vazias
colunas_para_remover = ['atingiu_pv', 'nota_ing','nota_mat','nota_por','rec_psicologia', 'indicado',]
df_definitivo = df_definitivo.drop(columns=[col for col in colunas_para_remover if col in df_definitivo.columns])
df_definitivo = df_definitivo.dropna(subset=['ra', 'pedra', 'fase'])

# Preenchendo valores nulos (NaN) das notas e indicadores com a MEDIANA
colunas_para_preencher = [
    'inde', 'iaa', 'ieg', 'ips', 'ida', 'ipv', 'ian', 'ipp'
]
for col in colunas_para_preencher:
    if col in df_definitivo.columns:
        df_definitivo[col] = df_definitivo[col].fillna(df_definitivo[col].median())

# Limpando espaços e aplicando 1ª letra Maiúscula
colunas_texto = ['genero', 'pedra', 'fase_ideal', 'instituicao_ensino']
for col in colunas_texto:
    if col in df_definitivo.columns:
        df_definitivo[col] = df_definitivo[col].astype(str).str.strip().str.title()
        df_definitivo[col] = df_definitivo[col].replace('Nan', np.nan)

# Substituindo nomes divergentes para um padrão único
df_definitivo['genero'] = df_definitivo['genero'].replace({'Menino': 'Masculino', 'Menina': 'Feminino'})
df_definitivo['pedra'] = df_definitivo['pedra'].replace({'Agata': 'Ágata', 'Topazio': 'Topázio'})

# Transformando a 'fase_ideal' em números (0 a 8)
fases_numericas = df_definitivo['fase_ideal'].astype(str).str.extract(r'(?i)fase\s*(\d+)')[0]

df_definitivo['fase_ideal'] = fases_numericas.fillna(0).astype(int)

In [24]:
# Binarizando a coluna Instituição de Ensino

def classificar_escola(nome_escola):
    nome = str(nome_escola).lower()

    privadas = ['privada', 'particular', 'decisão', 'decisao', 'jp ii', 'joão paulo', 'joao paulo']
    publicas = ['pública', 'publica', 'estadual', 'municipal'] # Adicionei estadual/municipal que significam pública

    if any(palavra in nome for palavra in privadas):
        return 'Privada'
    elif any(palavra in nome for palavra in publicas):
        return 'Pública'
    else:
        return 'Não Classificada'

# Aplicando a função na coluna
df_definitivo['instituicao_ensino'] = df_definitivo['instituicao_ensino'].apply(classificar_escola)

# Mantendo apenas as pedras válidas
pedras_validas = ['Quartzo', 'Ametista', 'Ágata', 'Topázio']
df_definitivo = df_definitivo[df_definitivo['pedra'].isin(pedras_validas)].copy()

## 4. Criando a variável Alvo (TARGET) do Modelo

In [25]:
# Risco = 1 (Quartzo ou Ágata) | Risco = 0 (Ametista ou Topázio)
df_definitivo['risco_defasagem'] = np.where(df_definitivo['pedra'].isin(['Quartzo', 'Ágata']), 1, 0)

# CONFERÊNCIA

print("--- Valores Únicos após a Padronização ---")
print(f"Gênero: {df_definitivo['genero'].unique()}")
print(f"Pedra: {df_definitivo['pedra'].unique()}")

print("\n--- Distribuição da Variável Target (Risco) ---")
print(df_definitivo['risco_defasagem'].value_counts())

print("\n--- Valores Nulos Restantes ---")
print(df_definitivo.isnull().sum())

--- Valores Únicos após a Padronização ---
Gênero: ['Feminino' 'Masculino']
Pedra: ['Quartzo' 'Ametista' 'Ágata' 'Topázio']

--- Distribuição da Variável Target (Risco) ---
risco_defasagem
0    1482
1     936
Name: count, dtype: int64

--- Valores Nulos Restantes ---
ano                   0
ra                    0
nome                  0
idade                 0
genero                0
fase                  0
turma                 0
ano_ingresso          0
instituicao_ensino    0
inde                  0
pedra                 0
fase_ideal            0
defasagem             0
iaa                   0
ieg                   0
ips                   0
ida                   0
ipv                   0
ian                   0
ipp                   0
risco_defasagem       0
dtype: int64

In [26]:
df_definitivo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2418 entries, 0 to 2928
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ano                 2418 non-null   int64
 1   ra                  2418 non-null   object
 2   nome                2418 non-null   object
 3   idade               2418 non-null   Int64
 4   genero              2418 non-null   object
 5   fase                2418 non-null   Int64
 6   turma               2418 non-null   object
 7   ano_ingresso        2418 non-null   Int64
 8   instituicao_ensino  2418 non-null   object
 9   inde                2418 non-null   float64
 10  pedra               2418 non-null   object
 11  fase_ideal          2418 non-null   int64
 12  defasagem           2418 non-null   float64
 13  iaa                 2418 non-null   float64
 14  ieg                 2418 non-null   float64
 15  ips                 2418 non-null   float64
 16  ida                 2418 non-null   float64
 17  ipv                 2418 non-null   float64
 18  ian                 2418 non-null   float64
 19  ipp                 2418 non-null   float64
 20  risco_defasagem     2418 non-null   int64
dtypes: Int64(3), float64(9), int64(3), object(6)
memory usage: 422.7+ KB

In [27]:
# verificando as colunas do df_definitivo
print("Colunas restantes:", df_definitivo.columns.tolist())
print("\nTipos de dados da Fase Ideal:")
print(df_definitivo['fase_ideal'].value_counts().sort_index())

Colunas restantes: ['ano', 'ra', 'nome', 'idade', 'genero', 'fase', 'turma', 'ano_ingresso', 'instituicao_ensino', 'inde', 'pedra', 'fase_ideal', 'defasagem', 'iaa', 'ieg', 'ips', 'ida', 'ipv', 'ian', 'ipp', 'risco_defasagem']

Tipos de dados da Fase Ideal:
fase_ideal
0     73
1    194
2    674
3    642
4    270
5    217
6    171
7    142
8     35
Name: count, dtype: int64

In [28]:
# SALVANDO O DATASET DEFINIVO (pede_completo.csv)
df_definitivo.to_csv('pede_completo.csv', index=False, sep=';', decimal=',')
print("\n✅ Sucesso! O arquivo 'pede_completo.csv' foi salvo.")

✅ Sucesso! O arquivo 'pede_completo.csv' foi salvo.